// All tunable numbers of the prototype live here (mirrors the spec-lite table).
export const P = {
    cols: 5,
    rows: 6,
    startMoves: 30,
    maxMoves: 40,
    movesPerLine: 12,
    initialFixed: 3,
    fixedGrowEvery: 2,
    maxFixed: 7,
    // Difficulty: the board's real optimum (moves to the first clear) must be
    // at least solveBase + floor(lines * solveRampPerLine), capped at solveMax.
    solveBase: 6,
    solveRampPerLine: 0.5,
    solveMax: 10,
    scrambleExtraSteps: 8,
    scrambleMinPulls: 4,
    scramblePullProb: 0.85,
    spawnAttempts: 300,
    solveNodeCap: 60000,
    decoys: 2,
    keepLeftover: 2,
    cellSize: 80,
    canvasW: 480,
    canvasH: 800,
    boardTop: 110,
    swipeMinPx: 24,
    popMs: 220,
    pruneBlinkMs: 120,
    pruneFadeMs: 500,
    walkStepMs: 70,
    maxUndo: 200,
    inputGuardMs: 400,
} as const;
