// Every number with gameplay weight lives here (see docs/spec.md "パラメータ表" and "演出・UI").
export const PARAMS = {
    viewW: 1024,
    viewH: 768,
    boardCols: 8,
    boardRows: 6,
    holeSpacing: 320,
    // portrait layout (docs/spec/portrait.md): same 48 holes and spacing, a taller view
    portraitViewW: 768,
    portraitViewH: 1024,
    portraitBoardCols: 6,
    portraitBoardRows: 8,
    hudMargin: 16,
    gameSeconds: 60,
    firstSpawnDelayMs: 500,
    spawnIntervalMs: 1200,
    maxActive: 4,
    friendRate: 0.25,
    decoyRate: 0.3,
    comboRate: 0.2,
    comboSize: 3,
    telegraphMs: 800,
    popLifetimeMs: 3000,
    hitRadius: 70,
    scoreMole: 10,
    scoreFriend: -20,
    scrollSpeed: 700,
    dragThresholdPx: 10,
    arrowMargin: 40,
    edgeScrollZonePx: 90,
    edgeScrollSpeed: 600,
    endingMs: 500,
    inputGuardMs: 300,
    hitShakeMs: 70,
    hitShakeIntensity: 0.003,
    catFlashMs: 180,
    catFlashColor: { r: 255, g: 40, b: 40 },
    catFlashAlpha: 0.35,
    arrowScale: 1.4,
    arrowPulseAmp: 0.1,
    arrowPulsePeriodMs: 500,
    floatTextRisePx: 70,
    floatTextMargin: 24,
    lowTimeSeconds: 10,
    lowTimePulse: 0.2,
    sceneFadeMs: 200,
    catShakeMs: 260,
    catShakeIntensity: 0.012,
    // presentation values the spec gives as "about" figures
    bodyRadius: 50,
    dustWidth: 120,
    dustHeight: 50,
    riseMs: 150,
    squashMs: 160,
    starCount: 8,
    starMs: 350,
    starSpread: 90,
    floatTextMs: 600,
    catFlyMs: 400,
    catFlyHeight: 160,
    ringMs: 300,
    retractMs: 150,
} as const;
