// Prototype parameters. The table in docs/spec.md must match this file.
export const P = {
    viewW: 1024,
    viewH: 768,
    boardCols: 8,
    boardRows: 6,
    holeSpacing: 320,
    gameSeconds: 60,
    spawnIntervalMs: 1200,
    maxActive: 4,
    friendRate: 0.25,
    comboRate: 0.2,
    comboSize: 3,
    telegraphMs: 800,
    popLifetimeMs: 3000,
    hitRadius: 70,
    scoreMole: 10,
    scoreFriend: -20,
    scrollSpeed: 700,
    dragThresholdPx: 10,
    arrowMargin: 40,
    edgeScrollZonePx: 90,
    edgeScrollSpeed: 600,
} as const;
